
services:
  node-backend:
    build: ./node-backend/
    ports:
      - "3000:3000"
    depends_on:
      - python-api
      - postgres-db
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres-db:5432/nousfit

  python-api:
    build: ./python_api
    ports:
      - "5000:5000"

  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nousfit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: